# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true

# edit here to achieve your personal greatness
url: https://www.nicolafiorillo.com
title: Nicola Fiorillo
author: Nicola Fiorillo
description: Personal web site
avatar: profile.png
email: nicola.fiorillo@gmail.com
github: nicolafiorillo # username
twitter: nicolafiorillo
linkedin: nicolafiorillo
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: nicolafiorillo

google_analytics: UA-50625867-1

# needed for travis-ci build
exclude: [vendor]
